# Generated by Django 4.1.3 on 2022-12-26 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskTitle', models.CharField(max_length=100)),
                ('taskDesc', models.CharField(max_length=2000)),
                ('time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
